/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingRequest } from '../../models/booking-request';

export interface CreateBookingRequest$Params {
      body: Array<BookingRequest>
}

export function createBookingRequest(http: HttpClient, rootUrl: string, params: CreateBookingRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BookingRequest>>> {
  const rb = new RequestBuilder(rootUrl, createBookingRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BookingRequest>>;
    })
  );
}

createBookingRequest.PATH = '/booking';
