/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingHistory } from '../../models/booking-history';

export interface GetBookingHistory$Params {
}

export function getBookingHistory(http: HttpClient, rootUrl: string, params?: GetBookingHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BookingHistory>>> {
  const rb = new RequestBuilder(rootUrl, getBookingHistory.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BookingHistory>>;
    })
  );
}

getBookingHistory.PATH = '/booking/user';
