/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookingHistory {
  bookedDate?: string;
  bookingId?: number;
  checkInDate?: string;
  checkOutDate?: string;
  floorNumber?: number;
  roomNumber?: number;
  towerNumber?: number;
  userName?: string;
}
