/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DailyMeal {
  breakfast?: string;
  dinner?: string;
  id?: number;
  lunch?: string;
  mealDate?: string;
}
