/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FoodPreferenceDto {
  breakfast?: boolean;
  dinner?: boolean;
  lunch?: boolean;
  mealDate?: string;
  preferences?: string;
  userId?: string;
  userName?: string;
}
