/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Room {
  floorNumber?: number;
  furnitures?: string;
  isAvailable?: boolean;
  roomCapacity?: number;
  roomCount?: number;
  roomId?: number;
  roomNumber?: number;
  roomType?: string;
  towerNumber?: number;
}
