/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequest {
  assoId: string;
  assoLevel: string;
  email: string;
  firstName: string;
  lastName: string;
  mobileNumber: number;
  password: string;
  roleId: number;
}
