/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DailyMeal } from '../models/daily-meal';
import { getMeal } from '../fn/daily-meal-controller/get-meal';
import { GetMeal$Params } from '../fn/daily-meal-controller/get-meal';
import { insertMeal } from '../fn/daily-meal-controller/insert-meal';
import { InsertMeal$Params } from '../fn/daily-meal-controller/insert-meal';

@Injectable({ providedIn: 'root' })
export class DailyMealControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getMeal()` */
  static readonly GetMealPath = '/dailyMeal';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMeal()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMeal$Response(params?: GetMeal$Params, context?: HttpContext): Observable<StrictHttpResponse<DailyMeal>> {
    return getMeal(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMeal$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMeal(params?: GetMeal$Params, context?: HttpContext): Observable<DailyMeal> {
    return this.getMeal$Response(params, context).pipe(
      map((r: StrictHttpResponse<DailyMeal>): DailyMeal => r.body)
    );
  }

  /** Path part for operation `insertMeal()` */
  static readonly InsertMealPath = '/dailyMeal';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insertMeal()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insertMeal$Response(params: InsertMeal$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return insertMeal(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insertMeal$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insertMeal(params: InsertMeal$Params, context?: HttpContext): Observable<{
}> {
    return this.insertMeal$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
