/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Room } from '../../models/room';

export interface GetAllRooms$Params {
}

export function getAllRooms(http: HttpClient, rootUrl: string, params?: GetAllRooms$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Room>>> {
  const rb = new RequestBuilder(rootUrl, getAllRooms.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Room>>;
    })
  );
}

getAllRooms.PATH = '/rooms';
