/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FoodPreferenceDto } from '../../models/food-preference-dto';

export interface GetAllFoodPreference$Params {
}

export function getAllFoodPreference(http: HttpClient, rootUrl: string, params?: GetAllFoodPreference$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FoodPreferenceDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllFoodPreference.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FoodPreferenceDto>>;
    })
  );
}

getAllFoodPreference.PATH = '/food/preference';
