/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { BookingHistory } from './models/booking-history';
export { BookingRequest } from './models/booking-request';
export { DailyMeal } from './models/daily-meal';
export { FoodPreferenceDto } from './models/food-preference-dto';
export { Room } from './models/room';
export { RoomUpdateRequest } from './models/room-update-request';
export { UserRequest } from './models/user-request';
