/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { RoomControllerService } from './services/room-controller.service';
export { BookingControllerService } from './services/booking-controller.service';
export { FoodPreferenceControllerService } from './services/food-preference-controller.service';
export { DailyMealControllerService } from './services/daily-meal-controller.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
